name: mpi-cluster

x-common-service: &common-service-template
  build:
    context: .
    dockerfile: Dockerfile
  networks:
    - my-net
  volumes:
    - type: bind
      source: /home/jakub/Code/BML/bml-big-1
      target: /workspace
      #read_only: true

services:
  
    container1:
      <<: *common-service-template
      container_name: container1
      ports:
        - "1022:22"
      command: /bin/bash -c "/setup.sh"
    
      
    container2:
      <<: *common-service-template
      container_name: container2
      ports:
        - "2022:22"
      
    
      
    container3:
      <<: *common-service-template
      container_name: container3
      ports:
        - "3022:22"
      
    
      
    container4:
      <<: *common-service-template
      container_name: container4
      ports:
        - "4022:22"
      
    
      
    container5:
      <<: *common-service-template
      container_name: container5
      ports:
        - "5022:22"
      
    
      
    container6:
      <<: *common-service-template
      container_name: container6
      ports:
        - "6022:22"
      
    
      
    container7:
      <<: *common-service-template
      container_name: container7
      ports:
        - "7022:22"
      
    
      
    container8:
      <<: *common-service-template
      container_name: container8
      ports:
        - "8022:22"
      
    
      
    container9:
      <<: *common-service-template
      container_name: container9
      ports:
        - "9022:22"
      
    
      
    container10:
      <<: *common-service-template
      container_name: container10
      ports:
        - "10022:22"
      
    
      
    container11:
      <<: *common-service-template
      container_name: container11
      ports:
        - "11022:22"
      
    
      
    container12:
      <<: *common-service-template
      container_name: container12
      ports:
        - "12022:22"
      
    
      
    container13:
      <<: *common-service-template
      container_name: container13
      ports:
        - "13022:22"
      
    
      
    container14:
      <<: *common-service-template
      container_name: container14
      ports:
        - "14022:22"
      
    
      
    container15:
      <<: *common-service-template
      container_name: container15
      ports:
        - "15022:22"
      
    
      
    container16:
      <<: *common-service-template
      container_name: container16
      ports:
        - "16022:22"
      
    
    
networks:
  my-net:
